### ISSUE TITLE
Not working in react-codemirror

### ISSUE THREAD

**Issue by Garyoook** [aatauil/codemirror-lang-sparql#1]
Hi,
I'm so glad that someone is writing support for sparql, right now the sparql() seems not working in my react-codemirror, have you met this problem before?
<img width="476" alt="image" src="https://user-images.githubusercontent.com/27125768/221937764-7ad40c79-4f50-4486-93ba-919ceeafb93f.png">

**Comment by aatauil** [comment]
Hi there! it is a tiny bit too early to use this parser as it still needs some work Luckily I have been working on a standalone editor and integrated it into a react project. 

You can find the standalone editor here: https://github.com/aatauil/sparql-editor. Still need to write a readme, for a usage example you can check the [index.html](https://github.com/aatauil/sparql-editor/blob/master/test/index.html ) in de test folder. the editor is not yet fully featured but is enough to get you going quickly.

This is the react project that uses the standalone editor: https://github.com/aatauil/sparql-browser-extension. The file most interesting to you will be the Editor.tsx component file: https://github.com/aatauil/sparql-browser-extension/blob/master/src/components/Editor.tsx, it has some stuff you probably will not need so here is a stripped down version:

```
import React, { useEffect, useRef, useState } from 'react';
import { createSparqlEditor } from 'sparql-editor';

function Editor() {
  const container = useRef()
  const [view, setView] = useState()

  useEffect(() => {
    if(file && !view) {
      const viewCurrent = createSparqlEditor({
        parent: container.current,
        onChange: onChange,
        value: "" // Default value
      })

      setView(viewCurrent)
    }
  }, [container, view, file?.id]);

  useEffect(() => {
    if(view) {
      view.destroy()
      setView(undefined)
    }
  }, [file?.id]);

  function onChange(value, viewUpdate) {
    // Do Some stuff
  }

  return (
    <div ref={container}><div>
  )
}

export default Editor
```

Good luck! Feel free to continue the thread if you're stuck

**Comment by Garyoook** [comment]
> Hi there! it is a tiny bit too early to use this parser as it still needs some work Luckily I have been working on a standalone editor and integrated it into a react project.
> 
> You can find the standalone editor here: https://github.com/aatauil/sparql-editor. Still need to write a readme, for a usage example you can check the [index.html](https://github.com/aatauil/sparql-editor/blob/master/test/index.html) in de test folder. the editor is not yet fully featured but is enough to get you going quickly.
> 
> This is the react project that uses the standalone editor: https://github.com/aatauil/sparql-browser-extension. The file most interesting to you will be the Editor.tsx component file: https://github.com/aatauil/sparql-browser-extension/blob/master/src/components/Editor.tsx, it has some stuff you probably will not need so here is a stripped down version:
> 
> ```
> import React, { useEffect, useRef, useState } from 'react';
> import { createSparqlEditor } from 'sparql-editor';
> 
> function Editor() {
>   const container = useRef()
>   const [view, setView] = useState()
> 
>   useEffect(() => {
>     if(file && !view) {
>       const viewCurrent = createSparqlEditor({
>         parent: container.current,
>         onChange: onChange,
>         value: "" // Default value
>       })
> 
>       setView(viewCurrent)
>     }
>   }, [container, view, file?.id]);
> 
>   useEffect(() => {
>     if(view) {
>       view.destroy()
>       setView(undefined)
>     }
>   }, [file?.id]);
> 
>   function onChange(value, viewUpdate) {
>     // Do Some stuff
>   }
> 
>   return (
>     <div ref={container}><div>
>   )
> }
> 
> export default Editor
> ```
> 
> Good luck! Feel free to continue the thread if you're stuck

Thanks!
